api/urls.py
from django.urls import path

from .views import FileUpload, GetProgress, GetUploadURL, ProcessUploadedFile

app_name = "api"

urlpatterns = [
    path('file-upload/', FileUpload.as_view(), name="file_upload"),
    path('get-upload-url/', GetUploadURL.as_view(), name="get_upload_url"),
    path('process-file/', ProcessUploadedFile.as_view(), name="process_file"),
    path(
        'get-import-progress/<str:task_id>/',
        GetProgress.as_view(),
        name="get_progress"
    ),
]

product/urls.py
from django.urls import path

from .views import HomePage, ProductList, ProductImport

app_name = "products"

urlpatterns = [
    path('', HomePage.as_view(), name="homepage"),
    path('products/', ProductList.as_view(), name="product_list"),
    path('import-products/', ProductImport.as_view(), name="product_import"),
]

product_importer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=512)
    sku = models.CharField(max_length=512, unique=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "product"
        ordering = ["name"]

api/views.py
# Django Import
from django.conf import settings

# DRF Imports
from rest_framework import status
from rest_framework.generics import CreateAPIView, RetrieveAPIView
from rest_framework.parsers import MultiPartParser
from rest_framework.response import Response

# App Imports
from .serializers import FileUploadSerializer, ProcessFileUploadSerializer
from product.constants import TaskStates

# Other imports
from celery.result import AsyncResult
import boto3
import time


# I have not designed user login and permission modules so all APIs are open


class FileUpload(CreateAPIView):
    serializer_class = FileUploadSerializer
    parser_classes = [MultiPartParser]
    permission_classes = []
    authentication_classes = []

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            {"message": "upload successful", "task_id": serializer.task_id},
            status=status.HTTP_202_ACCEPTED
        )


class GetProgress(RetrieveAPIView):
    permission_classes = []
    authentication_classes = []

    def get(self, request, task_id, *args, **kwargs):
        result = AsyncResult(task_id)
        # We don't need internal error message to show up in client side.
        if result.state == TaskStates.FAILURE:
            details = {"message": "Invalid File Uploaded"}
        else:
            details = result.info

        return Response({"state": result.state, "details": details})


class GetUploadURL(RetrieveAPIView):

    def get(self, request, **kwargs):
        filename = request.query_params.get("filename")
        if filename:
            filename = "tmp/" + filename
        else:
            filename = "tmp/" + str(time.time()) + ".csv"
        s3 = boto3.client(
            's3',
            region_name=settings.AWS_S3_REGION_NAME,
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY
        )
        bucket = settings.AWS_STORAGE_BUCKET_NAME

        return Response(
            s3.generate_presigned_post(
                Bucket=bucket,
                Key=filename,
                Fields={},
                Conditions=[],
                ExpiresIn=3600
            )
        )


class ProcessUploadedFile(CreateAPIView):
    serializer_class = ProcessFileUploadSerializer
    permission_classes = []
    authentication_classes = []

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            {"message": "Proceesing File", "task_id": serializer.task_id},
            status=status.HTTP_202_ACCEPTED
        )

product/views.py
# Django imports
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, ListView
from django.views.generic.base import View


# App imports
from .models import Product
from .utils import CustomPaginator


class HomePage(View):

    def get(self, request, **kwargs):
        # If products are there then redirect to list page otherwise ask user
        # to upload products
        if Product.objects.all().count():
            return HttpResponseRedirect(reverse_lazy("products:product_list"))
        else:
            return HttpResponseRedirect(reverse_lazy(
                "products:product_import")
            )


class ProductImport(TemplateView):
    template_name = "product/importer.html"


class BulkActions(View):
    """ To bulk delete or make inactive/active products. """

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        bulk_action = self.request.POST.get('bulk-action')
        # ids of products
        bulk_action_items = self.request.POST.getlist('item_ids[]', [])
        select_across = self.request.POST.get('select_across')

        if select_across:
            products = Product.objects.all()
        else:
            products = Product.objects.filter(id__in=bulk_action_items)

        if bulk_action == "delete":
            self.bulk_delete(products)
        elif bulk_action == "activate":
            self.bulk_change_state(products, True)
        elif bulk_action == "deactivate":
            self.bulk_change_state(products, False)
        return self.redirectresponse_success_url()

    def bulk_delete(self, products):
        products.delete()
        return self.redirectresponse_success_url()

    def bulk_change_state(self, products, is_active):
        products.update(is_active=is_active)
        return self.redirectresponse_success_url()

    def redirectresponse_success_url(self):
        if self.request.GET:
            queryparameter = "?" + self.request.GET.urlencode()
        else:
            queryparameter = ""
        return HttpResponseRedirect(self.success_url + queryparameter)


class ProductList(BulkActions, ListView):
    model = Product
    paginate_by = 20
    paginator_class = CustomPaginator
    success_url = reverse_lazy("products:product_list")

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.order_by("name")
        query = self.request.GET.get("q")
        filter_by = self.request.GET.get("filter_by", "").lower()
        if query:
            # Get all product that has query in name or sku
            qs = qs.filter(
                Q(name__icontains=query) | Q(sku__icontains=query)
            )
        if filter_by == "inactive":
            qs = qs.filter(is_active=False)
        elif filter_by == "active":
            qs = qs.filter(is_active=True)
        return qs

product/templates/product/importer.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">  
    <title>Home Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body style="height: 100vh">
    
    <div class="row d-none">
      <input type="file" name="_file" id='excel-input-file'>
    </div>   
    
    <div id="progress-wrapper">
      <div id="progress-bar" style="background-color: blue; width: 0%;">&nbsp;</div>
      <div id="progress-bar-message"></div>
      <div id="import-summary"></div>
    </div> 
    <div>
      <div id="final-message"></div> 
    </div>
    <div class="container" style="position: relative; top: 50vh; width: 100vw">
      <div class="col-md-12 text-center">
        <!--Import button-->
        <button type="button" class="btn btn-primary" id="import-button" 
                onclick="document.getElementById('excel-input-file').click()">
          Import Products
        </button>

        <!--product list-->
        <a href="{% url 'products:product_list' %}" class="btn btn-primary" id="product-list">
          Go to product list page
        </a>
        
        <!--loader-->
        <div id='upload-loader'>
          <div class="spinner-grow" role="status">
            <span class="sr-only">Uploading file please wait...</span>
          </div>
          <div>Uploading file please wait...</div>
        <div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script>

    $('#product-list').hide();
    $('#upload-loader').hide();
    (function () {
        var fileInputElm = document.getElementById('excel-input-file');
        fileInputElm.addEventListener('change', uploadFile, false);
    })();

    var task_id = null;
    function uploadFile(e) {
      var _file = e.target.files[0]; 
      $.ajax({
        url: "{% url 'api:get_upload_url' %}",
        type: 'GET',
        success: function (data) {
            $('#import-button').hide();
            console.log("got data======>", data)
            uploadFileToS3(_file, data.url, data.fields);
        },
        cache: false,
        contentType: false,
        processData: false
      });
    };
    
    function uploadFileToS3(_file, url, fields){
      let formData = new FormData(); 
      formData.append("key", fields.key);
      formData.append("x-amz-algorithm", fields["x-amz-algorithm"]);
      formData.append("x-amz-credential", fields["x-amz-credential"]);
      formData.append("x-amz-date", fields["x-amz-date"]);
      formData.append("policy", fields.policy);
      formData.append("x-amz-signature", fields["x-amz-signature"]);
      formData.append("file", _file);
      var file_path = fields.key
      $.ajax({
        url: url,
        type: 'POST',
        enctype:"multipart/form-data",
        data: formData,
        beforeSend: function() {
          $('#upload-loader').show();
        },
        success: function (data) {
          processUploadedFile(file_path);
        },
        cache: false,
        contentType: false,
        processData: false
      });
    }
    
    function processUploadedFile(file_path) {
      console.log("file_path======>", file_path)
      $.ajax({
        url: "{% url 'api:process_file' %}",
        type: 'POST',
        data: JSON.stringify({'file_path': file_path}),
        contentType: "application/json; charset=UTF-8",
        success: function (data) {
          $('#upload-loader').hide();
          task_id = data.task_id;
          var url = getProgressUrl();
          getProgressData(url);
        },
        cache: false,
        processData: false
      });
    }

    function getProgressUrl() {
      var progressUrl = window.location.origin + "/api/get-import-progress/" + task_id;
      return progressUrl
    }

    function getProgressData (progressUrl) {
      fetch(progressUrl).then(function(response) {
        response.json().then(function(data) {
          // update the appropriate UI components
          if (data.state === "PROGRESS") {
            setProgress(data.state, data.details);
            setTimeout(getProgressData, 500, progressUrl);
          } else if (data.state === "SUCCESS") {
            $('#progress-bar').hide();
            $('#progress-bar-message').hide();
            $("#final-message").text(data.details.message)
            $("#import-summary").text(
              'Imported: ' + data.details.valid_products + 
              ' Rejected: ' + data.details.invalid_products
            );
            $('#product-list').show();
          } else if (data.state === "FAILURE") {
            $('#import-button').show();
            $("#final-message").text(data.details.message)
          } else {
            // Probably in pending state, backend will update state to progress
            // in the second iteration.
            setTimeout(getProgressData, 500, progressUrl);
          }
        });
      });
    }
    
    function updateProgressBar(progressBarElement, progressBarMessageElement, importSummaryElement, progress) {
      progressBarElement.style.width = progress.percent + "%";
      progressBarMessageElement.innerHTML = progress.current + ' of ' + progress.total + ' processed.';
      importSummaryElement.innerHTML = 'Imported: ' + progress.valid_products + ' Rejected: ' + progress.invalid_products;
    }
  
    function setProgress(state, details) {
      var bar = document.getElementById("progress-bar");
      var barMessage = document.getElementById("progress-bar-message");
      var importSummary = document.getElementById("import-summary");
      var total = details.total;
      var done = details.done;
      var valid_products = details.valid_products;
      var invalid_products = details.invalid_products;
      var percent = (done * 100) / total;
      for (var i = 0; i < 11; i++) {
        updateProgressBar(bar, barMessage, importSummary, {
          percent: percent,
          current: done,
          total: total,
          valid_products: valid_products,
          invalid_products: invalid_products
        })
      }
    }
    
  </script>
  <style>
    #progress-bar {
      margin-top: 1em;
    }
  </style>
  </body>
</html>

product/templates/product/product_list.html
{% load static %}
{% load template_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">  
    <title>Product List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
  <body>
    
      <form method="get">
        <div class="row">
          <input class="col-3 form-control" name="q" id="search-input" type="text" placeholder="Type name and SKU to search" value="{{ request.GET.q }}">
          <div class="col-3">
            <div class="form-check">
              <input class="form-check-input" type="radio" name="filter_by" id="Radios1" value="all" 
                    {% if not request.GET.filter_by or request.GET.filter_by == "all" %} checked {% endif %}>
              <label class="form-check-label" for="Radios1">
                All
              </label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="filter_by" id="Radios2" value="active"
                    {% if request.GET.filter_by == "active" %} checked {% endif %}>
              <label class="form-check-label" for="Radios2">
                Active
              </label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="filter_by" id="Radios3" value="inactive"
                    {% if request.GET.filter_by == "inactive" %} checked {% endif %}>
              <label class="form-check-label" for="Radios3">
                Inactive
              </label>
            </div>
          </div>
          <button type="submit" class="col-2 btn btn-primary">Apply Search and Filter</button>
        </div>
      </form>

      <a href="{% url 'products:product_import' %}" class="col-1 float-right btn btn-primary">
        Import Products
      </a>


    <form method="post" id="bulk-action-form">
      <div class="form-group">
        <input type="checkbox" id="select-all">
        <label for="select-all">Check this select all products in system</label>
        <button class="btn btn-primary" type="submit" name="bulk-action" value="delete">Bulk Delete</button>
        <button class="btn btn-primary" type="submit" name="bulk-action" value="activate">Bulk Activate</button>
        <button class="btn btn-primary" type="submit" name="bulk-action" value="deactivate">Bulk Deactivate</button>
      </div>
    </form>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">
            <div class="container">
            <input type="checkbox" class="bulk-check-input" id="bulk-main-check">
            <label></label>
            </div>
          </th>
          <th scope="col">Name</th>
          <th scope="col">SKU</th>
          <th scope="col">Description</th>
          <th scope="col">Is Active</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
        <tr>
          <th scope="row">
          <div class="container">
            <input type="checkbox" class="bulk-check-input" value="{{object.id}}">
          </div></th>
          <td>{{ object.name }}</td>
          <td>{{ object.sku }}</td>
          <td>{{ object.description }}</td>
          {% if object.is_active %}
            <td><i class="fa fa-check" aria-hidden="true"></i></td>
          {% else %}
            <td><i class="fa fa-times" aria-hidden="true"></i></td>
          {% endif%}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="col-12 col-xxl-9">
        {% if page_obj.has_other_pages %}
        <nav class="mt-3">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}" tabindex="-1"><i class="fa fa-chevron-left"></i></a>
            </li>
            {% endif %}
            {% for page_number in page_obj.pagination_list %}
            <li class="page-item {% if not page_number or page_number == page_obj.number %}disabled{% endif %}"><a class="page-link" href="?{% url_replace page=page_number %}">{{page_number|default:"..."}}</a></li>

            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}"><i class="fa fa-chevron-right"></i></a>
            </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>
      // If main selection is toggle then toggle all childs
      $('#bulk-main-check').change(function() {
        if(this.checked) {
          $('.bulk-check-input').each(function() { $(this).prop('checked', true) }); 
        } else {
          $('.bulk-check-input').each(function() { $(this).prop('checked', false) }); 
        }
      });
      
      // If any checkbox states changes then hide/unhide forms
      $('.bulk-check-input').change(function() {
        if ($(".bulk-check-input:checked").length > 0){
          $('#bulk-action-form').show();
        } else {
          $('#bulk-action-form').hide();
        }
      })
      $( "#bulk-action-form" ).submit(function( event ) {
        var select_all = $("#select-all:checked").length > 0;
        // If select all is not selected then find id of each product and 
        // append to form else send select_across value as true.
        if (!select_all) {
          var item_ids = [];
          $('.bulk-check-input:checked').map(function () {
            if ($(this).val() !== "on") {
              item_ids.push($(this).val());
            }
          });
          $.each(item_ids, function(i, v){
            var input = $("<input>").attr({"type":"hidden","name":"item_ids[]"}).val(v);
            $('#bulk-action-form').append(input);    
          });
        } else {
          $("<input />").attr("type", "hidden")
            .attr("name", "select_across")
            .attr("value", true)
            .appendTo("#bulk-action-form"); 
        }
        return true
      });
      // Hide bulk form initially
      $('#bulk-action-form').hide();
    </script>
  </body>
</html>

product_importer/product/templates/product/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">  
    <title>Home Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body style="height: 100vh">
    
    <div class="row d-none">
      <input type="file" name="_file" id='excel-input-file'>
    </div>   
    
    <div id="progress-wrapper">
      <div id="progress-bar" style="background-color: blue; width: 0%;">&nbsp;</div>
      <div id="progress-bar-message"></div>
      <div id="import-summary"></div>
    </div> 
    <div>
      <div id="final-message"></div> 
    </div>
    <div class="container" style="position: relative; top: 50vh; width: 100vw">
      <div class="col-md-12 text-center">
        <button type="button" class="btn btn-primary" id="import-button" 
                onclick="document.getElementById('excel-input-file').click()">
          Import Products
        </button>
        <a href="{% url 'products:product_list' %}" class="btn btn-primary" id="product-list">
          Go to product list page
        </a>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script>

    $('#product-list').hide();
    (function () {
        var fileInputElm = document.getElementById('excel-input-file');
        fileInputElm.addEventListener('change', uploadFile, false);
    })();

    var task_id = null;
    function uploadFile(e) {
      var files = e.target.files;      
      let formData = new FormData(); 
      formData.append("_file", files[0]);
      $.ajax({
        url: "{% url 'api:file_upload' %}",
        type: 'POST',
        data: formData,
        success: function (data) {
            $('#import-button').hide();
            task_id = data.task_id;
            var url = getProgressUrl();
            getProgressData(url);
        },
        cache: false,
        contentType: false,
        processData: false
      });
    };

    function getProgressUrl() {
      var progressUrl = window.location.href + "api/get-import-progress/" + task_id;
      return progressUrl
    }

    function getProgressData (progressUrl) {
      fetch(progressUrl).then(function(response) {
        response.json().then(function(data) {
          // update the appropriate UI components
          if (data.state === "PROGRESS") {
            setProgress(data.state, data.details);
            setTimeout(getProgressData, 500, progressUrl);
          } else if (data.state === "SUCCESS") {
            $("#final-message").text(data.details.message)
            $("#import-summary").text(
              'Imported: ' + data.details.valid_products + 
              ' Rejected: ' + data.details.invalid_products
            );
            $('#product-list').show();
          } else if (data.state === "FAILURE") {
            $('#import-button').show();
            $("#final-message").text(data.details.message)
          } else {
            // Probably in pending state, backend will update state to progress
            // in the second iteration.
            setTimeout(getProgressData, 500, progressUrl);
          }
        });
      });
    }
    
    function updateProgressBar(progressBarElement, progressBarMessageElement, importSummaryElement, progress) {
      progressBarElement.style.width = progress.percent + "%";
      progressBarMessageElement.innerHTML = progress.current + ' of ' + progress.total + ' processed.';
      importSummaryElement.innerHTML = 'Imported: ' + progress.valid_products + ' Rejected: ' + progress.invalid_products;
    }
  
    function setProgress(state, details) {
      var bar = document.getElementById("progress-bar");
      var barMessage = document.getElementById("progress-bar-message");
      var importSummary = document.getElementById("import-summary");
      var total = details.total;
      var done = details.done;
      var valid_products = details.valid_products;
      var invalid_products = details.invalid_products;
      var percent = (done * 100) / total;
      for (var i = 0; i < 11; i++) {
        updateProgressBar(bar, barMessage, importSummary, {
          percent: percent,
          current: done,
          total: total,
          valid_products: valid_products,
          invalid_products: invalid_products
        })
      }
    }
    
  </script>
  <style>
    #progress-bar {
      margin-top: 1em;
    }
  </style>
  </body>
</html>